name: Compile LaTeX Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install LuaLaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full
    - name: Compile LaTeX Document
      run: |
        lualatex template.tex
    - name: Upload PDF to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: template_pdf
        path: template.pdf
